[build]
base = "sp500-dashboard"
command = "npm run build"
publish = "build"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"
REACT_APP_API_URL = "https://sp500-day-tradingbot.onrender.com"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.production.environment]
REACT_APP_API_URL = "https://sp500-day-tradingbot.onrender.com"

[context.deploy-preview.environment]
REACT_APP_API_URL = "https://sp500-day-tradingbot.onrender.com"
