services:
  - type: web
    name: sp500-trading-bot-api
    env: python
    buildCommand: "pip install --force-reinstall --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT sp500-api.src.main:app"
    plan: free
    region: oregon
    branch: main
    rootDir: .
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: FLASK_ENV
        value: production
      - key: TZ
        value: "Europe/Brussels"
    healthCheckPath: /api/status
